require 'matrix'
require 'sparse-matrix/vector'
require 'sparse-matrix/sparse_vector'
require 'sparse-matrix/sparse_matrix'
require 'sparse-matrix/coercion_helper'
require 'sparse-matrix/conversion_helper'